# Generated by Django 5.2.5 on 2026-07-04 15:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='New Coach Chat', max_length=180)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('duration_days', models.PositiveSmallIntegerField(default=30)),
                ('started_on', models.DateField(default=django.utils.timezone.localdate)),
                ('completed_days', models.PositiveSmallIntegerField(default=0)),
                ('badge', models.CharField(blank=True, max_length=120)),
                ('certificate_url', models.URLField(blank=True)),
                ('leaderboard_score', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('workout_reminder', 'Workout Reminder'), ('meal_reminder', 'Meal Reminder'), ('challenge_reminder', 'Challenge Reminder'), ('report_ready', 'Report Ready'), ('recommendation', 'Recommendation')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('plan_type', models.CharField(choices=[('workout', 'Workout'), ('nutrition', 'Nutrition'), ('transformation', 'Transformation'), ('supplement', 'Supplement'), ('equipment', 'Equipment'), ('body_explorer', 'Body Explorer'), ('chat', 'Chat')], db_index=True, max_length=30)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('response_json', models.JSONField(default=dict)),
                ('source_context', models.JSONField(blank=True, default=dict)),
                ('prompt_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('is_saved', models.BooleanField(db_index=True, default=True)),
                ('duplicated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coach.coachplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('event_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('rest', 'Rest'), ('missed', 'Missed')], db_index=True, default='planned', max_length=20)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='coach.coachplan')),
            ],
            options={
                'ordering': ['event_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
            ],
            options={
                'verbose_name': 'Nutrition Plan',
                'verbose_name_plural': 'Nutrition Plans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('coach.coachplan',),
        ),
        migrations.CreateModel(
            name='TransformationPlan',
            fields=[
            ],
            options={
                'verbose_name': 'Transformation Plan',
                'verbose_name_plural': 'Transformation Plans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('coach.coachplan',),
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
            ],
            options={
                'verbose_name': 'Workout Plan',
                'verbose_name_plural': 'Workout Plans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('coach.coachplan',),
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField(blank=True)),
                ('structured_content', models.JSONField(blank=True, default=dict)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='coach.aiconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('body_fat', models.FloatField(blank=True, null=True)),
                ('chest', models.FloatField(blank=True, null=True)),
                ('waist', models.FloatField(blank=True, null=True)),
                ('arms', models.FloatField(blank=True, null=True)),
                ('legs', models.FloatField(blank=True, null=True)),
                ('strength', models.FloatField(blank=True, null=True)),
                ('completed_workouts', models.PositiveIntegerField(default=0)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField(db_index=True)),
                ('week_end', models.DateField(db_index=True)),
                ('summary_json', models.JSONField(default=dict)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('is_ready', models.BooleanField(db_index=True, default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['user', '-last_message_at'], name='coach_aicon_user_id_1e35ab_idx'),
        ),
        migrations.AddIndex(
            model_name='coachnotification',
            index=models.Index(fields=['user', 'read_at', '-created_at'], name='coach_coach_user_id_8849dd_idx'),
        ),
        migrations.AddIndex(
            model_name='coachplan',
            index=models.Index(fields=['user', 'plan_type', '-created_at'], name='coach_coach_user_id_8188ea_idx'),
        ),
        migrations.AddIndex(
            model_name='coachplan',
            index=models.Index(fields=['user', 'prompt_hash', '-created_at'], name='coach_coach_user_id_01f0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'event_date', 'status'], name='coach_calen_user_id_55a42c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='coach_conve_convers_54eee3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progresshistory',
            unique_together={('user', 'recorded_on')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together={('user', 'week_start')},
        ),
    ]
