services:
  - type: web
    name: rediron-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_PUBLISH_KEY
        sync: false
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.smtp.EmailBackend"
      - key: EMAIL_HOST
        value: "smtp-relay.brevo.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "RedIron Gym <kvamsim7@gmail.com>"
      - key: ADMIN_EMAIL
        sync: false
      - key: SHOP_ADMIN_EMAIL
        sync: false
      - key: EMAIL_TIMEOUT
        value: "10"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://roaring-scone-cfda07.netlify.app"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://roaring-scone-cfda07.netlify.app"
      - key: LOAD_ALL_DATA
        value: "false"
