# Generated by Django 5.2.5 on 2025-10-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_paymentintent_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auto_payment',
            field=models.BooleanField(default=True),
        ),
    ]
