# Generated by Django 5.2.5 on 2025-10-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_subscription_user_razorpaypayment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RazorpayPayment',
        ),
    ]
