# Generated by Django 5.1.1 on 2026-01-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_is_verified_customuser_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clerk_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='Clerk user ID from Clerk authentication service', max_length=255, null=True, unique=True),
        ),
    ]
