# Generated by Django 5.2.5 on 2025-09-01 16:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment_images/')),
                ('usage', models.TextField(blank=True)),
                ('video_link', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('cardio', 'Cardio'), ('gym', 'Gym'), ('abs', 'Abs'), ('bodyweight', 'Bodyweight'), ('other', 'Other')], default='other', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('author', models.CharField(default='RedIron Team', max_length=120)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True, help_text='Markdown or HTML content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('featured_image_url', models.URLField(blank=True, help_text='Optional remote image URL')),
                ('category', models.CharField(choices=[('Nutrition', 'Nutrition'), ('Supplements', 'Supplements'), ('Recipes', 'Recipes')], default='Nutrition', max_length=40)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('reading_time', models.PositiveSmallIntegerField(blank=True, help_text='Minutes', null=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('author', models.CharField(default='RedIron Team', max_length=120)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True, help_text='Markdown or HTML content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='workout_articles/')),
                ('featured_image_url', models.URLField(blank=True, help_text='Optional remote image URL')),
                ('category', models.CharField(choices=[('Workout Tips', 'Workout Tips'), ('Fitness', 'Fitness')], default='Workout Tips', max_length=40)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('reading_time', models.PositiveSmallIntegerField(blank=True, help_text='Minutes', null=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/')),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('exercise_type', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('mobility', 'Mobility'), ('hiit', 'HIIT'), ('other', 'Other')], default='strength', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Full detailed explanation, benefits, how-to, tips, and challenge for this exercise.', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.ManyToManyField(blank=True, related_name='exercises', to='main.equipment')),
                ('primary_muscles', models.ManyToManyField(related_name='primary_exercises', to='main.musclegroup')),
                ('secondary_muscles', models.ManyToManyField(blank=True, related_name='secondary_exercises', to='main.musclegroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='workouts/')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ManyToManyField(blank=True, related_name='workouts', to='main.equipment')),
                ('muscle_groups', models.ManyToManyField(blank=True, related_name='workouts', to='main.musclegroup')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('sets', models.PositiveIntegerField(default=3)),
                ('reps', models.CharField(default='10-12', max_length=50)),
                ('rest_seconds', models.PositiveIntegerField(default=60)),
                ('notes', models.TextField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.workout')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
