# Generated by Django 5.2.4 on 2025-07-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='equipment_images/')),
                ('usage', models.TextField()),
                ('video_link', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Equipmient',
        ),
    ]
