# Generated by Django 5.2.5 on 2025-09-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionarticle',
            name='references',
            field=models.JSONField(blank=True, help_text='List of reference dicts for the article', null=True),
        ),
    ]
