# Generated by Django 5.2.5 on 2025-10-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_nutritionarticle_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionarticle',
            name='content',
            field=models.JSONField(blank=True, help_text='Structured JSON content with overview, key_benefits, etc.', null=True),
        ),
    ]
