# Generated by Django 5.2.5 on 2026-06-22 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_workouttip'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable fixture ID, e.g. FA01', max_length=20, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('category', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Strength Training', 'Strength Training'), ('Fat Loss', 'Fat Loss'), ('Recovery', 'Recovery'), ('Mobility', 'Mobility'), ('Nutrition', 'Nutrition')], db_index=True, default='Beginner', max_length=60)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='fitness_articles/')),
                ('featured_image_url', models.URLField(blank=True, help_text='Optional remote image URL')),
                ('author', models.CharField(default='RedIron Team', max_length=120)),
                ('overview', models.TextField(blank=True)),
                ('core_concepts', models.JSONField(blank=True, default=list)),
                ('why_it_matters', models.JSONField(blank=True, default=list)),
                ('science_explained', models.JSONField(blank=True, default=list)),
                ('practical_application', models.JSONField(blank=True, default=list)),
                ('common_myths', models.JSONField(blank=True, default=list)),
                ('coach_insight', models.TextField(blank=True)),
                ('key_takeaways', models.JSONField(blank=True, default=list)),
                ('video_title', models.CharField(blank=True, max_length=250)),
                ('youtube_url', models.URLField(blank=True)),
                ('related_articles', models.JSONField(blank=True, default=list, help_text='List of related FitnessArticle codes')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('reading_time', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='fitnessarticle',
            index=models.Index(fields=['category', 'is_published'], name='main_fitnes_categor_05a4c4_idx'),
        ),
        migrations.AddIndex(
            model_name='fitnessarticle',
            index=models.Index(fields=['slug'], name='main_fitnes_slug_880d3e_idx'),
        ),
    ]
