# Generated by Django 5.2.4 on 2025-07-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_equipment_delete_equipmient'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('gym', 'Gym'), ('abs', 'Abs')], default='gym', max_length=20),
        ),
    ]
