# Generated by Django 5.2.5 on 2025-10-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_import_nutrition_json'),
    ]

    operations = [
    ]
