# Generated by Django 5.2.4 on 2025-07-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contactmessage_alter_equipment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('Membership', 'Membership'), ('Billing', 'Billing'), ('Personal Training', 'Personal Training'), ('Others', 'Others')], max_length=50),
        ),
    ]
