# Generated by Django 5.2.5 on 2026-06-23 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_exercise_library_rebuild'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musclegroup',
            options={'ordering': ['parent__name', 'name']},
        ),
        migrations.RenameIndex(
            model_name='workouttip',
            new_name='main_workou_categor_f89282_idx',
            old_name='main_workou_categor_b43e08_idx',
        ),
        migrations.RenameIndex(
            model_name='workouttip',
            new_name='main_workou_slug_420fb4_idx',
            old_name='main_workou_slug_8143c8_idx',
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='body_region',
            field=models.CharField(blank=True, choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('legs', 'Legs'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('abs', 'Abs'), ('cardio', 'Cardio')], db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.musclegroup'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, help_text='Legacy video URL. New UI uses youtube_url first.', null=True),
        ),
        migrations.AlterField(
            model_name='musclegroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='musclegroup',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='musclegroup',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_muscle_group_per_parent'),
        ),
    ]
