# Generated by Django 5.2.5 on 2025-10-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20251029_0012'),
    ]

    operations = [
    ]
