# Generated by Django 5.2.5 on 2026-06-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_musclegroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionarticle',
            name='code',
            field=models.CharField(blank=True, help_text='Stable fixture ID, e.g. N01', max_length=20, null=True, unique=True),
        ),
    ]
