# Generated by Django 5.2.5 on 2025-10-29 13:23

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20251029_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
        ),
    ]
