# Generated by Django 5.2.5 on 2026-06-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_fitnessarticle_camelcase_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclegroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=140),
        ),
    ]
