# Generated by Django 5.2.5 on 2026-07-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_workouttip_featured_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BodyMetrics',
        ),
        migrations.RemoveField(
            model_name='exerciselog',
            name='session',
        ),
        migrations.DeleteModel(
            name='NutritionLog',
        ),
        migrations.DeleteModel(
            name='UserGoal',
        ),
        migrations.DeleteModel(
            name='ExerciseLog',
        ),
        migrations.DeleteModel(
            name='WorkoutSession',
        ),
    ]
