# Generated by Django 5.2.5 on 2025-10-29 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_fix_exercise_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
