# Generated by Django 5.1.1 on 2026-02-22 17:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_exercise_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_user_id', models.CharField(db_index=True, help_text='Clerk user ID for data isolation', max_length=255)),
                ('weight', models.FloatField(help_text='Body weight in kg')),
                ('body_fat', models.FloatField(blank=True, help_text='Body fat percentage', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['clerk_user_id', '-recorded_at'], name='main_bodyme_clerk_u_953185_idx')],
            },
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_user_id', models.CharField(db_index=True, help_text='Clerk user ID for data isolation', max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein', models.FloatField(default=0, help_text='Protein in grams')),
                ('carbs', models.FloatField(default=0, help_text='Carbs in grams')),
                ('fat', models.FloatField(default=0, help_text='Fat in grams')),
                ('water', models.FloatField(default=0, help_text='Water intake in liters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['clerk_user_id', '-date'], name='main_nutrit_clerk_u_e4a965_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_user_id', models.CharField(db_index=True, help_text='Clerk user ID for data isolation', max_length=255, unique=True)),
                ('goal_type', models.CharField(choices=[('fat_loss', 'Fat Loss'), ('muscle_gain', 'Muscle Gain'), ('strength', 'Strength'), ('endurance', 'Endurance')], default='muscle_gain', max_length=50)),
                ('target_value', models.FloatField(blank=True, help_text='Target value (e.g., weight, strength level)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['clerk_user_id'], name='main_usergo_clerk_u_0bf784_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_user_id', models.CharField(db_index=True, help_text='Clerk user ID for data isolation', max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('total_volume', models.FloatField(default=0, help_text='Auto-calculated total volume (weight × reps × sets)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['clerk_user_id', '-date'], name='main_workou_clerk_u_19cb2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=200)),
                ('sets', models.PositiveIntegerField(default=3)),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('calculated_1rm', models.FloatField(default=0, help_text='Auto-calculated 1RM using Epley formula')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='main.workoutsession')),
            ],
            options={
                'ordering': ['-session__date', '-created_at'],
            },
        ),
    ]
