# Generated by Django 5.2.5 on 2026-04-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_bodymetrics_nutritionlog_usergoal_workoutsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('core', 'Core')], default='cardio', max_length=20),
        ),
    ]
