# Generated by Django 5.1.1 on 2026-04-15 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rediron_shop', '0003_remove_userprofile_user_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_stats',
            field=models.JSONField(blank=True, default=list, help_text="Additional stat cards. E.g., [{'label': 'Max Weight', 'value': '150 KG', 'icon': 'weight'}]"),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.JSONField(blank=True, default=list, help_text="List of benefits/advantages. E.g., [{'title': 'Benefit 1', 'description': 'Desc'}]"),
        ),
        migrations.AddField(
            model_name='product',
            name='key_features',
            field=models.JSONField(blank=True, default=list, help_text="List of key features with icons. E.g., [{'title': 'Feature 1', 'description': 'Desc', 'icon': 'heart'}]"),
        ),
        migrations.AddField(
            model_name='product',
            name='perfect_for',
            field=models.JSONField(blank=True, default=list, help_text="Use cases. E.g., [{'label': 'Weight Loss', 'icon': 'target'}, ...]"),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=list, help_text="Equipment specifications. E.g., [{'label': 'Motor Power', 'value': '4.0 HP'}, ...]"),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube video URL for equipment', null=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='rediron_shop.product')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
